---
- name: Configure a gitlab server
  hosts: workstation
  become: yes
  vars:
    GITLAB_HOME: /srv/gitlab
  tasks:

## Install some dependancies
  - name: Ensure some software we need is installed
    dnf:
      name:
        - podman
      state: latest

  - name: Create a user to run the instance of gitlab
    user:
      name: gitlab_user
      password: '$6$9wPJ0z27n89oHMS0$KacO/4JlFcIJUeq5Up4lMvvQmxQzUOyEGoD4HUCgeUsuYdSlWifjV5PxH5XKmEYVsWTmCPD3IHPpFt/nqHVXz.'
      state: present
      system: yes
      createhome: no

## Pull the gitlab community edition container.
  - name: Pull latest gitlab-ce
    containers.podman.podman_image:
      name: gitlab/gitlab-ce
      tag: latest

## Set an environment variable to define location of gitlabg
  - name: set GITLAB_HOME
    become: false
    command: >-
      bash -c "export GITLAB_HOME={{ GITLAB_HOME }}"

## Create the directory to contain the logs, database and config
  - name: create directoriy
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
      owner: gitlab_user
      group: gitlab_user
    loop:
      - "{{ GITLAB_HOME }}/config"
      - "{{ GITLAB_HOME }}/logs"
      - "{{ GITLAB_HOME }}/data"

