---
- name: Configure a gitlab server
  hosts: workstation
  become: yes
  tasks:

## Install some dependancies
  - name: Ensure some software we need is installed
    dnf:
      name:
        - podman
      state: latest

  - name: Create a user to run the instance of gitlab
    user:
      name: gitlab_user
      password: '$6$9wPJ0z27n89oHMS0$KacO/4JlFcIJUeq5Up4lMvvQmxQzUOyEGoD4HUCgeUsuYdSlWifjV5PxH5XKmEYVsWTmCPD3IHPpFt/nqHVXz.'
      state: present
      system: yes
      createhome: no

## Pull the gitlab community edition container.
  - name: Pull latest gitlab-ce
    containers.podman.podman_image:
      name: gitlab/gitlab-ce
      tag: latest

## Set an environment variable to define location of gitlab config
## files, logs and the database files.
  - name: set GITLAB_HOME
    become: false
    command: >-
      bash -c "export GITLAB_HOME=/srv/gitlab"

